### ISSUE TITLE
Grand command renaming

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/vimwiki-pytasks#1]
One of the first things I might suggest, is to rename ALL of the commands!

That's right, all of them!

The original vimwiki-tasks is essentially undocumented, save for the commit messages, as each feature was added by teranex. Now don't get me wrong, the functions are amazingly clever, but the command names are undocumented and undiscoverable, and I think a new command-naming-scheme could really help that.

Take vim-taskwarrior as an excelent (and related) example. Ze He (the author) used "TWXxxXxx" in naming all vim-tw commands, and as a result, all vim-tw commands are easily seen in vim, with ":TW< tab >" completion. I don't consider this a conflict, I'm quite sure that Ze has no great plans to use "TWW" (or any new user-commands, actually) and that would make this program's commands discoverable while using that program!

and so I would nominate ":TWWXxxXxx" for all of this program's user-commands, because
- it will make all commands easily discoverable
- it's easy to type
- it's easy to remember (TaskWarrior Wiki)  

for example:

:TaskCmd 
becomes (simply) 
:TWW

:UpdateTaskList
becomes
:TWWUpdate

:InsertTasks
becomes
:TWWInsert

:DisplayTaskUUID
becomes
:TWWUuid

:CopyTaskUUID
becomes
:TWWCopyUuid

There may be existing commands I don't know about, and tons of room for new features and commands, but that should get the idea across.

**Comment by tbabej** [comment]
I don't mind consistent naming of the commands. If they get implemented, I will use consistent naming.

Currently no of the user commands are ported. But the plugin is so well written that each of these should be only couple of lines.
